# Generated by Django 3.1.4 on 2021-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20211107_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
