# Generated by Django 3.1.4 on 2021-09-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('roomname', models.CharField(max_length=40)),
                ('isanswer', models.BooleanField(default=False)),
                ('isfile', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, default='text', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoodleAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
