# Generated by Django 3.1.4 on 2021-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isimage',
            new_name='isfile',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, default='text', max_length=40, null=True),
        ),
    ]
