# Generated by Django 3.1.4 on 2021-09-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0002_room_userprofie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='roomname',
        ),
        migrations.RemoveField(
            model_name='userprofie',
            name='dp',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangochat.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofie',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
