# Generated by Django 3.1.4 on 2021-09-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangochat', '0003_auto_20210918_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomname',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
